### ISSUE TITLE
Temperature freezing bug.

### ISSUE THREAD

**Issue by KenanTheFab** [studio-minus/ppg-bug-reports#10]
**Describe the bug**
Freezes the scene until restarted.

**Clearly describe how to reproduce the bug**
Set the temperature to any value then hit the escape key/the menu key and then return to the scene.

**Mod list**
All mods disabled.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.17.2
 - GPU: RTX 2080
 - CPU: Ryzen 2700x

**Comment by mestiez** [comment]
fixed
