### ISSUE TITLE
Animated Modded guns Broken

### ISSUE THREAD

**Issue by Altronbee** [studio-minus/ppg-bug-reports#101]
**Describe the bug**
In mods that add animated weapons, some of them have their charging handles, bolts, slides etc layered BEHIND the weapon texture, this only started happening AFTER 1.21, during the 1.21 beta everything was working fine

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
Spawn in any modded weapon that has animated parts, some are layered Correctly, Some arent.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.
 DISABLED:
 HUMANS+ By 
 FleasyWeapons-RIfles By 
 Atuo-9 
 Dead No-collide By 
 Metal Humans 
 Zombie And Survivors Guns
 FleasyWeapons-Small Guns
 Guns,guns,guns!
 H.U.M.A.N Tech Mod [UPDATE 1.1]
 VanillaWeapons+ 3
 Madness Combat:Collection
 Configurable Explosive
 Old Textures Mod 
 Freshhold Towers
 Treshold Towers
 The ULTIMATE Minecraft Mod 
 COMBAT SPEC-OPS
 COMBAT SPEC-OPS MAP
 Better <PPG> weapons || unrealized mod
Retextured Nulls
Police+
PSK Mod
Demogorgon
Escape From Tarkov Weapons
Vanilla Weapons+ 2
Volcanic Map
Tactial Armors 
S.C.P.F mod
More Destructible Objects !
Vietnam Soldiers Mod
The Tungsten Mod
Active Humans 
CSGO Weapon
COMBAT Weapons Pack V3.0
Expanded Lightsabers
Weapons+
Weapon Mod

 ENDABLED:
 FIREARMADA - G/G/G/P/M By Jimmly & Bonible
 Counter-Strike Mod
 AutoAim
 Dune Bunker Laboratory
 OCM
 The Musket Mod
 Animated Weapons+
 Quality Of Life Items
 Scream Mod (DONT ASK.)
 Wheelchair
 flipping heck
 Colored Cars Mod
 Miltary+
 DOOM ETERNAL The Crucible Mod
 Aimbot Gun
 Trains and Freights MOD
 Per Pixel Destruction
 Madness PACK
 Legacy Gorse
 Controllable anti-air cannon
 Humans+ 
 Hold K To Make Wires Invisible
 
 
 
 
 

 

**System info (please complete the following information)**
 - Game version: [1.21]
[exported game debug info.md](https://github.com/studio-minus/ppg-bug-reports/files/7002654/exported.game.debug.info.md)

**Additional notes**

**Comment by Altronbee** [comment]
just tested it, after disabling all the mods except the ones the have broken weapons and they are still not working, has to be a game issue or the modders need to relayer the weapon parts

**Comment by mestiez** [comment]
Yes this is almost certainly related to #97 
To resolve this, modders need to properly adjust the layering on their parts.
