### ISSUE TITLE
Immortality Serum go bye-bye when things happen

### ISSUE THREAD

**Issue by SalreixVonOtsuu** [studio-minus/ppg-bug-reports#103]
**Describe the bug**
Immortality Serum disappears when shot at (or something?)

**Clearly describe how to reproduce the bug**
Inject human with immortality serum, then use a reconstructor on them, **or** just shoot them until they stop glowing and die

**Mod list**
Active: Raw Pink Liquids
Inactive: Android Injectors, Skittle's Syringe Mod, Functioning Armor, Soror's NPC pack, and Syringes++

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.21
 - GPU: I don't know
 - CPU: I don't know

**Additional notes**
I hope this is a bug because having to reapply it constantly would be annoying (also sorry for poor quality idk)

**Comment by SalreixVonOtsuu** [comment]
Also, immortality serum seems to override other effects?

**Comment by mestiez** [comment]
When a human has holes, liquid will leak out. All liquids, even immortality serum, will simply leak out of the person and its effects disappear. The Reconstructor removes the immortality serum as it considers any foreign liquid harmful.

**Comment by SalreixVonOtsuu** [comment]
Oh
I didn't know this, nor did I ever hear about it, and I also haven't seen this in effect the entire time I've played, so that's strange
