### ISSUE TITLE
Contraptions using mods, that are saved in 1.21 can't be loaded

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bug-reports#104]
**Describe the bug**
Contraptions using mods, that are saved in 1.21 can't be loaded

**Clearly describe how to reproduce the bug**
1. Spawn in 1 or more objects, **at least 1 of them has to be from a mod**.
2. Select the objects and save them.
3. Find it in your saved contraptions category.
Now no matter how much you click on it, it will make the noise but it will not select it, meaning you cannot spawn it.

## System info

 - **OS**: Windows 10  (10.0.19043) 64bit

 - **CPU**: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz

 - **GPU**: Intel(R) UHD Graphics

 - **Memory**: 7 GB

## All loaded mods

	zooi-Signals and Logic Gates-2504621801 v1.2 for game v1.18.1
		Currently ACTIVE
		Has been initialised

 
**Additional notes**
Just guessing but this is probably something to do with _"All contraptions saved from now on will include a list of required mods. When selecting a modded contraption, the game will display a list of required mods if you don't have them installed or enabled."_

**Comment by UniDuki** [comment]
This only happens if you have the mod installed, otherwise it correctly pops up with the dialogue box saying unfulfilled mod requirements

**Comment by mestiez** [comment]
Fixed :)
