### ISSUE TITLE
Context menu bug

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bug-reports#106]
If you press "resize" or "stop" resizing" context menu not closing so you need did second click outside context menu window to close it.

Open context menu and resize thing.

No mods.

Operating system: win 10
Game version: 1.21 beta
GPU: Nvidia geforce 750 TI
CPU: Intel Core I3-3240 3.40 GHz

**Comment by mestiez** [comment]
Fixed :)
