### ISSUE TITLE
Activation Toggle still functions when broken

### ISSUE THREAD

**Issue by SalreixVonOtsuu** [studio-minus/ppg-bug-reports#107]
**Describe the bug**
When an Activation Toggle part is broken (by bullet or EMP or explosion etc), it still gives an activation signal and can be turned on and off with no loss of function.

**Clearly describe how to reproduce the bug**
Turn it on, then shoot it or use an EMP/explosion. It isn't even affected by it.

**Mod list**
Raw Pink Liquids (active)

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.21
 - GPU: idk
 - CPU: idk

**Additional notes**
ok this one I'm sure is a bug
Also they don't have a disable machine heat damage but they aren't affected by heat in any way whatsoever atm so whatever

**Comment by mestiez** [comment]
Fixed :)
