### ISSUE TITLE
laser bug

### ISSUE THREAD

**Issue by estegod** [studio-minus/ppg-bug-reports#108]
**Describe the bug**
when you reduce the laser to a smaller size the laser sight stays in its position

**Clearly describe how to reproduce the bug**
reduce the size to a smaller size and activate the laser

**Mod list**
no mods

**System info (please complete the following information)**
 - Operating system: windows 10 x64
 - Game version:1.21
 - GPU: nvidia geforce 1050 ti
 - CPU: Intel(R) Core(TM) i5-4460

**Additional notes**

**Comment by mestiez** [comment]
Fixed :)
