### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by BugMan33** [studio-minus/ppg-bug-reports#109]
**Describe the bug**
In version 1.21.1 the maps are a little bit to the right side idk if its a bug or it should be like that but the real issue is when I hold E on  saved contraptions it shows completely random object and that object is every time random and it is like 100x bigger

**Clearly describe how to reproduce the bug**
idk if only I have that issue or other people too.

**Mod list**
- Activated - Death Note , Auto-9 , Raw Pink Liquids , Pickle Human , Quick Right Click Options , The Musket Mod , Wheelchair , FTC Weapons , Taser , Powers mod , Functioning armor  , Time Accelerator , Hold K to make wires invisible

- Deactivated -Metal Humans , Prototype 1 Mod , FleasyWeapons - Small Guns , Cyberpunk 2077 Trauma Medic Pack , Halo Weapons Reupload , Gorse , Injectable Flasks Mod , OCM , Animated Weapons+ , Greenbrick Industries , ExplosiveMod , The Better Acid Syringe , Weapons+

**System info (please complete the following information)**
 - Operating system: Windows 10 64 bit
 - Game version: 1.21.1
 - GPU: AMD Radeon™ RX 5500M
 - CPU: AMD Ryzen™ 7 4800H

![Bug](https://user-images.githubusercontent.com/89192183/130052254-28811f26-489f-428f-97cd-87eeff22cd43.jpg)

![20210819122056_1](https://user-images.githubusercontent.com/89192183/130052694-b88e5120-2aaf-40de-a2c8-83cb4702eea3.jpg)

**Comment by mestiez** [comment]
Can you try describing the issue more clearly?

**Comment by BugMan33** [comment]
> Can you try describing the issue more clearly?

So when I hold E to show the contraption before placing it into the game it is very big and it does not look like the contraption I want to place . On the picture with the truck you can see that  thing on left I held E to show the shadow of the small truck and on right I placed the truck and resized it  so the thing on the left is the truck in small version but it is showing random objects in very big size .

**Comment by mestiez** [comment]
Oh yes this has been fixed :)

**Comment by BugMan33** [comment]
> Oh yes this has been fixed :)

When ? I still have the issue .

**Comment by mestiez** [comment]
In the next update

**Comment by BugMan33** [comment]
> In the next update

ok thanks :)
