### ISSUE TITLE
Human has no burn effect

### ISSUE THREAD

**Issue by chefaf300** [studio-minus/ppg-bug-reports#12]
**Describe the bug**
when you burn a human, he doesnt burn, just dies, or acts in distress but still no effect
**Clearly describe how to reproduce the bug**
just burn the guy with anything lmfao

**Mod list**
none

**System info (please complete the following information)**
 - Operating system: 
 - Game version: 1.18
 - GPU: rtx 2070
 - CPU: ryzen 2700x

**Additional notes**

N/A

**Comment by mestiez** [comment]
idk why this suddenly happened but i fixed it
