### ISSUE TITLE
Burning human frame drops

### ISSUE THREAD

**Issue by ohitzjakey** [studio-minus/ppg-bug-reports#13]
When setting a human on fire my frames gradually drop from ~144 to ~20

Reproduce Bug:
1) select all humans limbs
2)Ignite
3)view frames dropping

**Mod list**
Futuristic Weapons Mod + - Gun_O                       Mo' Fluids -JGrimesGamed
more android - END                                                More Weapons Mod
Gorey Zombie Grunt -CliffyRocket038                    Configurable Explosive -Frosty
Gentle Drag                                                             Flasks. More of them. -ScriptMeat
Acid Firefly -Woowz11                                             Infection -Nexus
Jebus mod -FredMichalBear                                     Deams Explosives -holy_spirit
Metal Things Mod -Quickness                                Bombs Expanded -Kxtten
Nuclear Playground -Kubulll                                  !Unknown mod -woowz11
Toy Guns: Explosives! -Noname
Buff Human -talonphobia

System info
 - Operating system: Windows 10 Pro
 - Game version: 1.18.1
 - GPU: Gtx 1070 8gb
 - CPU: Ryzen 7 2700x

**Additional notes**
Thanks for the amazing game :)

**Comment by mestiez** [comment]
Are you sure this isn't the fault of the "Unknown Mod"?

**Comment by ohitzjakey** [comment]
> Are you sure this isn't the fault of the "Unknown Mod"?

Uninstalled the Unknown Mod and all is done! Thanks for the suggestion i hadn't thought it could be that
