### ISSUE TITLE
Issue with Saved Items

### ISSUE THREAD

**Issue by Rommist64** [studio-minus/ppg-bug-reports#15]
I apologize if this has already been said.

I just realized I am absolutely retarbeded and didn't properly make this. I apologize.

Describe the bug A clear and concise description of what the bug is.
Some save items are flagged as corrupted, always.

Clearly describe how to reproduce the bug Steps to reproduce the problem.
Try to place the following item:
https://steamcommunity.com/sharedfiles/filedetails/?id=2503052420
And upon clicking on the spawn icon it will pop a message saying something about it being corrupted.

Mod list Include a list of your mods here and specify whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.
I have tried with normal modlist (extensive), all disabled and recently uninstalled, reinstalled and cleared PPG Workshop cache. It does not work any way.

System info (please complete the following information)

Operating system: Windows 10
Game version: 1.18.1
GPU: NVIDIA GeForce GTX 1060 6GB
CPU: Intel(R) Core(TM) i7-9700K CPU @ 5.60Hz
Additional notes
On non-main drive, hard drive, opposed to main solid state (due to VR games)

**Comment by romist64** [comment]
Messed it up and I don't know how to delete it so I guess this is how?

**Comment by romist64** [comment]
I'm just gonna reopen it. I feel like I'm dying from embarrassment so I'm probably not gonna be here.

**Comment by mestiez** [comment]
This is not a bug. The contraption requires the scream mod (seemingly) and it doesn't say so.
