### ISSUE TITLE
tank glitches out

### ISSUE THREAD

**Issue by OofRun** [studio-minus/ppg-bug-reports#2]
tank glitches out after moving the cannon around

fling the tank, while its falling, pause the simulation, select the entire tank and move it anywhere, the tank cannon glitches. now that the tank's cannon is glitched, move the tank cannon around and it should happen

i am not using any mod right now

 - Operating system: windows 10
 - Game version: 1.17
 - GPU: AMD Athlon vega 3 graphics
 - CPU: AMD athlon 300u

note : the bug sometimes doesnt work

**Comment by mestiez** [comment]
fixed
