### ISSUE TITLE
Bullets create more splash particles the longer they are on water

### ISSUE THREAD

**Issue by weirdo001** [studio-minus/ppg-bug-reports#20]
**Describe the bug**
The longer a bullet tracer is touching a water surface, the more splash particles appear.

**Clearly describe how to reproduce the bug**
Shoot a bullet at water with tracers enabled and pause the game for a couple seconds, or even just enable slow motion.
![image](https://user-images.githubusercontent.com/85614742/121334222-79b77980-c8e7-11eb-875d-f3e8ae7b9a29.png)

[exported game debug info.md](https://github.com/studio-minus/ppg-bug-reports/files/6622871/exported.game.debug.info.md)

**Comment by mestiez** [comment]
fixed lmao
