### ISSUE TITLE
Game is black upon start up

### ISSUE THREAD

**Issue by BoredSkittle** [studio-minus/ppg-bug-reports#21]
Bug Description
Whenever I start the game up, it turns black, I can click stuff, just cant see. I managed to load into a map, but the game crashed upon loading

How to reproduce the bug.
I don't know how to reproduce it.

Mods active
I have no mods currently, as I deleted them, but the problem persisted.

System info
 - Operating system: Windows
 - Game version: 1.18.1
 - GPU: Intel(R) HD Graphics 3000
 - CPU: Intel i7

**Comment by mestiez** [comment]
What version of Windows

**Comment by mestiez** [comment]
Your graphics processor is incredibly old. It does pass the minimum requirements, but just barely. I wouldn't be surprised that its age may be the cause of your issues.

**Comment by mestiez** [comment]
required information not given :(
