### ISSUE TITLE
Defibrillator will be stuck in standby after repair if broken while in standby

### ISSUE THREAD

**Issue by BradFitz66** [studio-minus/ppg-bug-reports#23]
**Describe the bug**
If a defibrillator is destroyed while in standby mode (standby is written on the screen of the defib), when it's repaired via the right click context menu it will be in standby mode forever and can no longer be used

**Clearly describe how to reproduce the bug**
Spawn defibrillator
Activate it 
While it says standby, destroy it (energy sword works best)
Repair it and try to use it again, at which point you should see it still say standby and can no longer be used

**Mod list**
I have about 20 mods enabled, but the bug is still present will all of them disabled

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: Latest (1.18.1)
 - GPU: RTX 2080 Super with Max-Q Design
 - CPU: i7 10875H

**Additional notes**

**Comment by mestiez** [comment]
fixe
