### ISSUE TITLE
Friction? Who knows!

### ISSUE THREAD

**Issue by MidLaneAnnie** [studio-minus/ppg-bug-reports#24]
**Friction? Intentional? Who knows!**
Metallic objects becoming hot.

**Dragging metallic objects against the walls and or surfaces of the arena causes them to heat up, drastically.**
Step 1 : Pick an "x" metallic object i.e. a knife.
Step 2 : Use the move tool to press it against any surface hard.
Step 3 : Remove the object and take its tempature OR press it to a living being to make them burn.
Step 4 : Profit.

**Mod list : No Mods were used.**
No Mods were active.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.18.1
 - GPU: NVIDIA GeForce GTX 1050 Ti
 - CPU: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz   2.81 GHz

**I am not positive if its supposed to a feature or if its just a bug. But I really like this game a lot (despite being put on a list for playing it.) I wanna help!**

**Comment by mestiez** [comment]
Friction generates heat :), this is a feature.
