### ISSUE TITLE
Exact same "compiling a mod forever" issue yet again

### ISSUE THREAD

**Issue by WWWOWWWPL** [studio-minus/ppg-bug-reports#28]
**Describe the bug**
When I launch the game, a mod called Hingejoint2D.GameObject seems to be compiling forever. It adds some experimental syringes, so it happens probably because of 1.19's syringe overhaul

**Clearly describe how to reproduce the bug**
Load in a mod that contains pre-1.19 syringes (?) that has been deleted from the workshop

**Mod list**
[exported game debug info.md](https://github.com/studio-minus/ppg-bug-reports/files/6671592/exported.game.debug.info.md)

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.19 preview
 - GPU: Nvidia GeForce 1050ti
 - CPU: Intel Core i5 7600k quad-core

**Additional notes**
goddamn your game reworks

**Comment by mestiez** [comment]
the mod you are trying to load literally says "broken" in the title of it.
