### ISSUE TITLE
text mirrored for certain items

### ISSUE THREAD

**Issue by AMIT2421** [studio-minus/ppg-bug-reports#29]
**Describe the bug**
Items with text, like blood tank, liquidentifier, etc... have the text mirrored when placed to the left

**Clearly describe how to reproduce the bug**
place an item with text like: blood tank, liquidentifier with "q"

**Mod list**
No mods.

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.19 beta.
 - GPU: gtx 1060
 - CPU: intel core i7 8th gen

**Comment by mestiez** [comment]
this is not a bug. if you place the item flipped, the text will be flipped too.
