### ISSUE TITLE
Syringes with effects don't change color when injected

### ISSUE THREAD

**Issue by Tinotin1** [studio-minus/ppg-bug-reports#32]
**Describe the bug**
When using a syringe with an effect, such as the Life syringe, the color from the syringe doesn't fade to empty as it did in preview 1. The syringe still affects the being.

**Clearly describe how to reproduce the bug**
Inject any effect syringe into a being

**Mod list**
None

**System info (please complete the following information)**

    Operating system: Windows 10
    Game version: 1.19 preview 2
    GPU: Nvidia GTX 1660
    CPU: Intel Core i5 9400f

**Comment by mestiez** [comment]
syringes are infinite since preview 2, this is not a bug
