### ISSUE TITLE
Issue With Copy and Paste in Expanded Gore

### ISSUE THREAD

**Issue by Paulyfisk** [studio-minus/ppg-bug-reports#33]
Bug Description:
When expanded gore mode is enabled, copying and pasting a human will result in an odd bug occurs that causes the brain to appear outside of the human's head, the hit-box for the brain is completely moved, and causes some issues, making humans a pain to use in expanded gore mode if you need to copy and paste them.

Reproduce:
Go into the settings menu and the 9th setting (Expanded Gore) at toggle it on. Next select a human from the menu and spawn them. Right click and drag so that the entire human is in the select area, and copy the human. Paste the human, and the bug should appear.

Mods: N/A 

 - Operating system: Windows
 - Game version: 1.18.1
 - GPU: NVIDIA GeForce GTX 970
 - CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00 GHz
 
More Information: 
I am aware that expanded gore is not yet fully supported, but I felt that you should be made aware of the bug if you weren't already.

**Comment by mestiez** [comment]
expanded gore has been permanently discontinued quite a while ago, unfortunately
