### ISSUE TITLE
It isn't really a bug but more of a Coding error. It just doesn't make much sence when the tank, eats 30 nukes and still drive perfectly fine but when in water completely break the engine. No modes are enabled, and it still lived. Device name	LAPTOP-M6JC8L3O Processor	Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz Installed RAM	8.00 GB (7.70 GB usable) Device ID	7120B0EC-59CA-4B4E-9B96-89DC848D19D9 Product ID	00325-96655-65389-AAOEM System type	64-bit operating system, x64-based processor Pen and touch	No pen or touch input is available for this display 

### ISSUE THREAD

**Issue by Eggabegga** [studio-minus/ppg-bug-reports#34]
**Describe the bug**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**System info (please complete the following information)**
 - Operating system: 
 - Game version:
 - GPU:
 - CPU:

**Additional notes**

**Comment by mestiez** [comment]
Please read the instructions carefully

**Comment by Eggabegga** [comment]
Ok understood

**Comment by DindinYT37** [comment]
I had a stroke reading this after having found it.
