### ISSUE TITLE
almost fixed bug with limbs

### ISSUE THREAD

**Issue by YOPLAY13** [studio-minus/ppg-bug-reports#35]
a person is hurt when a torn part of the body heats up

**Clearly describe how to reproduce the bug**
video
**Mod list**
all disabled

**System info (please complete the following information)**
 - Operating system: win 10
 - Game version:1.9 (beta)
 - GPU: RX 570
 - CPU: Ryzen 5 1400

**Additional notes**
the bug is not fully fixed

https://user-images.githubusercontent.com/86079489/122534617-631dca80-d02b-11eb-9d08-eccf5f034f67.mp4

**Comment by mestiez** [comment]
fixe

**Comment by mestiez** [comment]
d
