### ISSUE TITLE
Humans not affected by Nitroglycerin.

### ISSUE THREAD

**Issue by WrillWasTaken** [studio-minus/ppg-bug-reports#36]
Humans are completely healthy after being injected with many times the lethal dose of Nitroglycerin, with the only side effect being sudden detonation. [How do I know this?](https://cdn.discordapp.com/attachments/855441226160668742/855441438036852776/1118200_screenshots_20210618143705_1.jpg)

**Clearly describe how to reproduce the bug**
Inject human with absurd amounts of Nitroglycerin

**Mod list**
None

**System info**
 - Operating system: Windows 10 home edition
 - Game version: 1.19 Preview 2
 - GPU:  NVIDIA GeForce GTX 1080 Ti
 - CPU: Intel(R) Core(TM) i7 -8700k CPU @3.70GHz

**Additional notes**
Not entirely sure if this is actually a bug or a missing gameplay feature.

**Comment by mestiez** [comment]
This is not a bug. It's a good feature request though.
