### ISSUE TITLE
Copying and pasting a new human breaks its neck

### ISSUE THREAD

**Issue by ReactionAndy** [studio-minus/ppg-bug-reports#37]
**Describe the bug**
After copying a freshly spawned human and pasting it out it immediately breaks it's neck

**Clearly describe how to reproduce the bug**
Pause Game - Optional
Select human in item list.
Spawn Human with E or Q
Select Human and copy it
Paste Human from copy
Unpause Game - Optional

**Mod list**
Flipping heck - Deactivated

**System info (please complete the following information)**
 - Operating system: Windows 10 Home - Version: 19041.1052
 - Game version: 1.19
 - GPU: NVIDIA GeForce GTX 1070
 - CPU: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz

**Additional notes**
If you where to inject the Human with the Life Syringe before copying it, makes it so that the neck does not break when copying it and pasting it.

**Comment by mestiez** [comment]
Cannot reproduce
