### ISSUE TITLE
v i b r a t i o n

### ISSUE THREAD

**Issue by WrillWasTaken** [studio-minus/ppg-bug-reports#39]
**Describe the bug**
Object intensely shakes and heats anything it touches (probably from mega fast vibration)
**Clearly describe how to reproduce the bug**
I have no freaking idea it just happens sometimes

[exported game debug info.md](https://github.com/studio-minus/ppg-bug-reports/files/6681380/exported.game.debug.info.md)

**Additional Notes:**
I've encountered this in other unity games and usually refer to it as the kraken. Which also probably means it's unity fuckery.

[I caught the kraken caught on video](https://youtu.be/9DfU6cymKKA)

**Comment by mestiez** [comment]
lmao yes i dont think im able to solve this
