### ISSUE TITLE
Burning is wayyy to fast now.

### ISSUE THREAD

**Issue by Sirblockhead1** [studio-minus/ppg-bug-reports#4]
**Describe the bug**
Previously, if you lit someone on fire, you had time to react and make sure they got taken care of. Now, you have but 3-5 seconds before they die when on fire.
**Clearly describe how to reproduce the bug**
-Light someone on fire
-Wait 3-5 Seconds

**Mod list**
This will occur even when no mods are activated.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.17.3
 - GPU: NVIDIA GeForce RTX 2080 SUPER
 - CPU: Intel Core i7-9700K

**Additional notes**

**Comment by mestiez** [comment]
they stay conscious and alive for much longer now.
