### ISSUE TITLE
heating element light won't go out when damaged

### ISSUE THREAD

**Issue by somepurplekale** [studio-minus/ppg-bug-reports#40]
**Describe the bug**
The small green light indicating whether a heating/cooling element is active or not doesn't turn off when the element is destroyed.

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
Spawn a heating element, activate it, and destroy it.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.
No mods were active.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.19
 - GPU: Radeon RX 560X
 - CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx 2.10 GHz

**Additional notes**

**Comment by mestiez** [comment]
finxed
