### ISSUE TITLE
Stielhandgranate Heat Damage Sprite Bug

### ISSUE THREAD

**Issue by BitEU** [studio-minus/ppg-bug-reports#41]
**Describe the bug**

https://user-images.githubusercontent.com/45499599/122658605-45d92100-d13d-11eb-9026-3f7f3685ce55.mp4
, when placed on a steel beam at 9999 degrees Celcius, explodes as it should. However, the model of the 
https://user-images.githubusercontent.com/45499599/122658605-45d92100-d13d-11eb-9026-3f7f3685ce55.mp4
 is still in the position where the explosion occurred, unaffected by the said explosion. The static model can still be moved, however. When the already discharged Stielhandgranate has activated again (because the model hasn't disappeared or changed into the exploded sprite), there is nothing.\

**Clearly describe how to reproduce the bug**
Place a Stielhandgranate on a steel beam at 9999 degrees Celcius and observe

**Mod list**
OCM
Marvel
Mafia
Androids Plus
Spec Ops
Police+
City People
WWS

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.19
 - GPU: Nvidia GTX 1050Ti
 - CPU: Intel Core i7-8700k

**Comment by mestiez** [comment]
I cannot reproduce this so it must be caused by a mod.
