### ISSUE TITLE
Simple Layer Bug

### ISSUE THREAD

**Issue by Eggabegga** [studio-minus/ppg-bug-reports#42]
The syringe Sprite overlaps on most soft blocks and stay on the top layer
![2021-06-20](https://user-images.githubusercontent.com/86094981/122665444-3d9cd800-d175-11eb-8572-84f4f24da876.png)

Device name	LAPTOP-M6JC8L3O
Processor	Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz
Installed RAM	8.00 GB (7.70 GB usable)
Device ID	7120B0EC-59CA-4B4E-9B96-89DC848D19D9
Product ID	00325-96655-65389-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by mestiez** [comment]
fixed

**Comment by Eggabegga** [comment]
Thanks
