### ISSUE TITLE
oil not killing people after they have been revived

### ISSUE THREAD

**Issue by AMIT2421** [studio-minus/ppg-bug-reports#43]
**Describe the bug**
oil cant kill a person after he was killed by oil injection and revived.

**Clearly describe how to reproduce the bug**
fill a syringe with oil. inject a human with the syringe. revive the human with life syringe or defibrillator. if you inject that human with an oil syringe again it will not kill him.

**Mod list**
no mods

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.19
 - GPU: gtx 1060
 - CPU: intel core i7 8th gen

**Additional notes**

**Comment by mestiez** [comment]
fixed
