### ISSUE TITLE
Infinite Oil Fuel Tanks

### ISSUE THREAD

**Issue by BitEU** [studio-minus/ppg-bug-reports#44]
**Describe the bug**
Car fuel tanks, when ripped out of cars, have infinite fluid in them

**Clearly describe how to reproduce the bug**
Rip out a car fuel tank, attach dozens of blood tanks via the blood vessel wires, set the tanks to pull, and watch as a never ending oil deposit is founded from said fuel tank

**Mod list**
OCM
Marvel
Mafia
Androids Plus
Spec Ops
Police+
City People
WWS

**System info (please complete the following information)**

    Operating system: Windows 10
    Game version: 1.19
    GPU: Nvidia GTX 1050Ti
    CPU: Intel Core i7-8700k

**Comment by mestiez** [comment]
It isn't infinite. You can fill a little over 71 blood tanks with a single fluid tank. Why is this? Because I just put "1000" without thinking.
