### ISSUE TITLE
humans stop holding items when something is changed in pause

### ISSUE THREAD

**Issue by OofPlayzStuff** [studio-minus/ppg-bug-reports#45]
When I tried to make a human hold in item in pause, it worked. But I noticed that when I changed the item in hand, or anything else, the item would fall because the human would let go.

Give a human an item to hold
Press "f" on the hand to make the human grab it
Modify the item or any other item
Then it should pop off.

**Mod list**
Simple Syringes Mod
VanillaWeapons+ 3
Animated Weapons+
Blocksify's Crazy Syringe Mod
Syringes++ (Reupload)
Copper Republic Mod
More Explosives
Android Injectors
ExplosiveMod
Special Forces Mod
Skittle's Syringe Mod
Chemical Warfare
Functioning Armor
Halo weapons
Soror's NPC Pack
Active Humans
CSGO Weapons
Syringes++
Lightsabers

 - Operating system: Windows 10
 - Game version: 1.19
 - GPU: Intel(R) UHD Graphics 620
 - CPU: Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz   2.30 GHz

**Additional notes**
I was using an "Active Human" and it did it with a regular one too. This only happened in 1.19.

**Comment by mestiez** [comment]
I cannot reproduce this.
