### ISSUE TITLE
I found a bug where if you mix liquid in an empty syringe, and i tried this with almost all the syringes (The Flasks Work). When I mix them and put them in an empty syringe, the effects don't mix and just have no effect at all. 

### ISSUE THREAD

**Issue by blitzerblurker** [studio-minus/ppg-bug-reports#46]
**Describe the bug**
I found a bug where if you mix liquid in an empty syringe, and i tried this with almost all the syringes (The Flasks Work). When I mix them and put them in an empty syringe, the effects don't mix and just have no effect at all. I did this with the death, bone-eating, and the flesh eating syringes, put them in the liquidifier, and put them in a syringe, no effect. No death, no acid, no bone eating. Please look into this. I wanna kill humans with all effects.

**Clearly describe how to reproduce the bug**
 I did this with the death, bone-eating, and the flesh eating syringes, put them in the liquidifier, and put them in a syringe, no effect. No death, no acid, no bone eating. Please look into this. I wanna kill humans with all effects. It should work with all syringes but the Life Syringe. That one works.

**Mod list**
OCM, Tazers, Gallows, Lighsabers, Jojo's Bizarre Adventure Mod.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.19
 - GPU:  NVIDIA GeForce RTX
 - CPU: Intel Core i5-7300HQ

**Additional notes**
The Flasks work when mixed and put into a human, but when added to the liquidifier as well and put into a syringe they don't work either.

**Comment by mestiez** [comment]
Are you sure the syringe isn't set to "pull" mode when you stick it into a human?

**Comment by mestiez** [comment]
Closing until I get a response.
