### ISSUE TITLE
People behaving strange

### ISSUE THREAD

**Issue by SkitTheBlueWolf** [studio-minus/ppg-bug-reports#47]
When the people entity is spawned they start to wobble if right clicked and instructed to walk the person will flail around or walk backwards and often break their neck or other bones overall being very unstable and unbalanced dragging limbs also causes flailing and bones to break.

**Mod list**
Human tech mod
Quick right click options
OCM (v.13)
Scream mod
Green brick industries
Mulligan
Green hammer
Halo weapons
Functioning armor
Chemical warfare
Teathers
Active humans
Lightsaber mod

**System info**
 - Operating system: Windows 10
 - Game version: 1.19
 - GPU: Nvidia GeForce GTX 1050
 - CPU: Intel(R) Core(TM) i7-7700

**Additional notes**
I have tried disabling all my mods and have the same issue

**Comment by mestiez** [comment]
I can reproduce this by lowering the "physics iterations" setting to values below 16. Have you done this?

**Comment by SkitTheBlueWolf** [comment]
I have not tried messing with the physics iteration settings yet I will try
that and report back to you if that fixes the issue

**Comment by mestiez** [comment]
Closed until further information is provided
