### ISSUE TITLE
Crushing limbs disable collisions

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bug-reports#48]
**Description**
Crushing a limb which is stabbed by one or multiple sharp objects will disable the collision of the said sharp objects completely with the living whose limb was crushed. Simply, stabbing a limb of an entity with a weapon and then crushing it will disable the weapon's collisions with the entity.

**How to reproduce**
- Spawn an entity with one or more limbs.
- Stab a limb with a weapon and keep the weapon intact.
- Crush the stabbed limb
- The weapon will no longer collide with the entity.

**Mod list**

No mods need to be present to reproduce the bug.

**System info**
 - Operating system: Linux Mint
 - Game version: 1.9.1
 - GPU: GeForce GTX 650 Ti BOOST
 - CPU: Intel(R) Core(TM) i7 @ 3.33GHz

**Additional notes**
The bug is reproducable on every living entity whose limb can be stabbed and crushed.

**Comment by mestiez** [comment]
im pretty sure i fixed it
