### ISSUE TITLE
Objects phase through people if thrown too hard.

### ISSUE THREAD

**Issue by IseAxon** [studio-minus/ppg-bug-reports#49]
Sometimes when you try to throw an object at a human it goes cleanly through them as if it had no collisions.

Steps: Spawn human, spawn an object, a knife in this case. Throw the knife hard at the human. In about 90% of cases, if not more, the knives just phase through the human harmlessly.

No active mods.

 - Operating system: Windows 10, 64 bit
 - Game version: 1.19.1
 - GPU: NVIDIA GeForce GTX 1050 Ti
 - CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 2808 Mhz, 4 Core(s), 8 Logical Processor(s)

This bug has been consistent for the past few updates.

**Comment by mestiez** [comment]
Not a bug. Enable "continuous" collision in your settings.
