### ISSUE TITLE
when dismembered limbs are crushed the host of the limb starts bleeding

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bug-reports#50]
**Describe the bug**
when a dismembered limb gets crushed the host starts bleeding for some unknown reason

**Clearly describe how to reproduce the bug**
tear off a limb of a human like the forearm patch up the human crush the limb and they will start bleeding again

**Mod list**
none

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.19.2
 - GPU: gtx 1650 super
 - CPU: intel i5

**Additional notes**

**Comment by mestiez** [comment]
:) fixed
