### ISSUE TITLE
Human save and load problem

### ISSUE THREAD

**Issue by WeegePeege** [studio-minus/ppg-bug-reports#52]
When I save a human to the local tab with an open flesh wound and I spawn that same human in and stab that wound, the flesh somewhat grows back.

spawn a human in, shoot it anywhere, save the human to the local tab, spawn the saved human in, stab or shoot the same area you made the wound, and it will grow back the flesh
 
Mod List: Madness mod V1.6.1, Syringes++ (REUPLOAD), Greenbrick Industries, Lightsabers, flipping heck, Overdose, Simple Syringes Mod, Humans+.

 - Operating system: Windows 10.
 - Game version: 1.19.2
 - GPU: GeForce RTX 2070 SUPER
 - CPU: AMD Ryzen 5 3600 6-Core Processor

**Comment by mestiez** [comment]
??? No need to post the same thing twice

**Comment by WeegePeege** [comment]
Sorry I had thought it had not saved
