### ISSUE TITLE
Access violation following a car into a decimator

### ISSUE THREAD

**Issue by StealthDrifter** [studio-minus/ppg-bug-reports#54]
was following a car into a decimator and the game crashed, here's the log. cant seem to be able to replicate it though maybe it could cause problems for other people if it happens again
[error.log](https://github.com/studio-minus/ppg-bug-reports/files/6758969/error.log)

**Comment by mestiez** [comment]
i hate unity

**Comment by mestiez** [comment]
the error log has little useful information because the epic™ unity crash handler failed to handle the crash (its only job).
from this lack of information, i can only imagine these causes:
 - Program ran out of memory
 - Your memory malfunctioned
