### ISSUE TITLE
liquidentifler text when spawned the opposite way round 

### ISSUE THREAD

**Issue by Beef-beef** [studio-minus/ppg-bug-reports#55]
**Describe the bug**
liquidentifler text when spawned in from the left ( Q ) is the opposite way round.

**Clearly describe how to reproduce the bug**
spawn the liquidentifler to the left

**Mod list**
none

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.19.2
 - GPU: NVIDIA GeForce GTX 1060 6GB
 - CPU: AMD Ryzen 5 3600XT 6-Core Processor

**Additional notes**

![Capture1](https://user-images.githubusercontent.com/82110509/124370508-79a16400-dc70-11eb-8f8d-7774a546ac21.PNG)

**Comment by mestiez** [comment]
This is not a bug. Spawning something flipped will make it spawn flipped.
