### ISSUE TITLE
syringes explode limbs

### ISSUE THREAD

**Issue by Koazzy** [studio-minus/ppg-bug-reports#56]
**Describe the bug**
when i try to use a modded syringe like my immortality syringe the limb i inject it into explodes as of the new update, but the syringe still works

**Clearly describe how to reproduce the bug**
i just have to inject a syringe from steam workshop into a limb and the the limb explodes (any limb ie, head, leg, arm etc)

**Mod list**
OCM
quick right click options
superluigicat's human mod
scream mod
greenbrick industries
clothes pack 2.0
bonibles furry pack
injectable flasks mod
happy wheels mod
wheelchair
flipping heck
city map
the ultimate minecraft mod
flasks. more of them
dream (character model)
active humans
syringes++

**System info (please complete the following information)**
 - windows 10 (free version): 
 - 1.19.2:
 - Nvidia rtx 2060 (6 gb vram):
 - ryzen 5 3600:

**Additional notes**

**Comment by pablogonzales2009** [comment]
i think that's the mods fault yk

**Comment by mestiez** [comment]
> i think that's the mods fault yk

this is correct. the mod developer has to consider the recent update. while i try to keep all mods working when updating, sometimes a sacrifice is necessary.
