### ISSUE TITLE
(Solved) my pc problems :d

### ISSUE THREAD

**Issue by NieumytyUmyslowo** [studio-minus/ppg-bug-reports#57]
**Describe the bug**
When u detach legs from a man they still alive and even if u do something to legs the rest of body getting harmed. (I used heal syringe only for the rest of body that was still alive)
**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
 delete legs by simply frooze the rest of body then use heal syringe to man shot legs and then he starts bleeding 
**Mod list**
Flippin Check by zool (off) 
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**System info (please complete the following information)**
 - Operating system:  Windows
 - Game version: 1.19.3
 - GPU: radeon Rx 570
 - CPU:amd ryzen 7 2700x

**Additional notes**
Even after unnistaling all mods from game still didnt work

**Comment by NieumytyUmyslowo** [comment]
ayo, 1 bug sorry :)

**Comment by mestiez** [comment]
yo how the f*uck do you have 1.19.3 its not even out yet

**Comment by EfeYks534** [comment]
> yo how the f*uck do you have 1.19.3 its not even out yet

He forgot to disable the magic mod
