### ISSUE TITLE
guided missile launcher bug

### ISSUE THREAD

**Issue by player8008** [studio-minus/ppg-bug-reports#59]
**Describe the bug**
the missile from the guided missile launcher will explode it immediately sometimes
**Clearly describe how to reproduce the bug**
shoot guided missile launcher, it will happen once you do it enough or maybe even first try(you dont need a target, it can happen either way)

**Mod list**
gore removal(deactivated)

 - Operating system: Windows 10
 - Game version: 1.19.2
 - GPU: not sure how to find out, apologies
 - CPU: same thing

 sorry couldnt find this either

**Additional notes**
all i know is that my system runs the game pretty smoothly but i am on a laptop so my specs are not that good, not sure if this may be the reason. the issue arose after i began playing again(which was in version 1.19.2.)

**Comment by KomodoBro** [comment]
Is it locked onto a target?

**Comment by mestiez** [comment]
fixed
