### ISSUE TITLE
Mouse cursor Drift 

### ISSUE THREAD

**Issue by GODZILLA0001** [studio-minus/ppg-bug-reports#6]
I don't know if this is jut my mouse becuase it's new but this only happens when I load up People Playground and when I close the game my cursor is perfectly fine again. When I load up the game it causes my mouse to very slowly move to the left of my screen without me touching the mouse buy as soon as the game closes the problem stops. And I have never had this issue although it is a new mouse however this has never happened in any other game I play so it has to be something to do with people playground. If no one else gets the problem then it's probs just becuase this is a newish mouse although the problems only started in 1.17 and I didn't have this problem with the mouse cursor in 1.16

**Comment by mestiez** [comment]
Please follow the bug report template
