### ISSUE TITLE
The Pink Syringe's Enhancing Serum may cause parts to burst

### ISSUE THREAD

**Issue by DavidCo113** [studio-minus/ppg-bug-reports#61]
**Describe the bug**
The liquid's code has a chance to reduce the breaking threshold and base strength of limbs. Also it works on Androids.

**Clearly describe how to reproduce the bug**
Inject a human with pure Enhancing Serum and watch

**Mod list**

	krzem-throwing knife-2540929350 v1.0 for game v1.19.2
		Currently inactive

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently inactive

	Aspa102-OCM-2508897711 v2.0 for game v1.19
		Currently inactive

	Mishanya-Animated Weapons+-2503670951 v1.6 for game v1.18.1+
		Currently inactive

	R0Y1T0-Half Life 2 PPG - Characters-2499110668 v2.0 for game v1.18x
		Currently inactive

	R0Y1T0-Half Life 2 PPG - Weapons-2495290530 v1.75 for game v1.18x
		Currently inactive

	Gun_O-Futuristic Weapons Mod +-2494447929 v0.3 for game v1.17
		Currently inactive

	zooi-Gentle Drag-2490855955 v1.0 for game v1.18 preview 1
		Currently inactive

	yefeyks-Generators+-2490397546 v1.0 for game v1.17.3
		Currently inactive

	Bangee-Russian CIty-local v1.0 for game v1.14+
		Currently inactive

	Kubulll-Nuclear Playground-2484034390 v0.9.1 for game v1.18+
		Currently inactive

	Skittles-1000 Degree Knife-local v1.0 for game vBETA I SWEAR TO GOD USE THE BETA, unless it updated
		Currently inactive

	PaulRiisk-Sherman Edition-local v1.0 for game v1.16+
		Currently inactive

	Aspa102-Wheelchair-2455335631 v1.0 for game v1.16+
		Currently inactive

	PaulRiisk-KV-2-local v1.0 for game v1.16+
		Currently inactive

	PaulRiisk-Tiger I-local v1.0 for game v1.16+
		Currently inactive

	trexxet-Weld Tool-local v1.0 for game v1.15+
		Currently inactive

	DANGER-Copper Republic Mod-2417633430 v1.3 for game v1.17
		Currently inactive

	NoName-Toy Guns!-local v1.0 for game v1.15
		Currently inactive

	ScriptMeat-Volcanic Map-2395054754 v1.1.2 for game v1.14+
		Currently inactive

	jimmyl-Android Injectors-2381177128 v1.4 for game v1.12+
		Currently inactive

	Frosty-Black Hole Syringe-local v1.0 for game v1.14
		Currently inactive
		Malfunctioning

	Morzzic-Taser-2361892819 v1.1 for game v1.11+
		Currently inactive

	jimmyl-Parts and Contraptions-2337159652 v3.9.5 for game v1.18+
		Currently inactive

	jimmyl-ExplosiveMod-2337158074 v1 for game v1.10+
		Currently inactive

	zooi-Per Pixel Destruction-2314372940 valpha 7 for game v1.13.1
		Currently inactive

	Alibarda-Human Tiers-2308911224 vv4.0 for game v1.12+
		Currently inactive

	Skittles-Skittle's Syringe Mod-2268097682 v1.4 for game v1.19+
		Currently inactive

	weirdo-Chemical Warfare-2226697361 v1.0 for game v1.16+
		Currently inactive

	Golden-Hazmat Mod Remastered-2217857980 v1.3.1 for game v1.9+
		Currently inactive

	Morzzic-Smart Spawner-2195054961 v2.2 for game v1.10+
		Currently inactive

	weirdo-Functioning Armor-2194511729 v1.0 for game v1.17
		Currently inactive

	Svit and Sky-POT O' Items-2187367733 v1.2 for game v1.9.4
		Currently inactive

	Sororfortuna-Soror's NPC Pack-2169243678 v11.0 for game v1.19.2
		Currently inactive

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently inactive

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently inactive

	(RU)Enot builder-Weapon Mod-2137486750 v0.8 for game v1.7x
		Currently inactive

	davidco7777-Black Hole Tool-2547353717 v1.0 for game v1.8+
		Currently inactive

	davidco7777-Crash Syringe-2549115710 v1.0 for game v1.19+
		Currently inactive

	davidco7777-Dye Liquids-2548144790 v1.0 for game v1.19+
		Currently inactive

	davidco7777-Raw Pink Liquids-2546503625 v1.0 for game v1.19+
		Currently ACTIVE

**System info**
 - **OS**: Windows 10  (10.0.19042) 64bit

 - **CPU**: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

 - **GPU**: NVIDIA GeForce GTX 1060 3GB

 - **Memory**: 16 GB

**Comment by mestiez** [comment]
Neat. Apparently this is intentional, I simply misnamed the liquid. The serum also has the chance to weaken the limbs to a point where they burst under extremely low pressure. I've changed it so that it will only improve the limb. Thanks for finding this :)
