### ISSUE TITLE
OCM zombie bug

### ISSUE THREAD

**Issue by grEE3n** [studio-minus/ppg-bug-reports#62]
Whenever you inject a human with the zombie syringe, they go limp.

1. Enable the OCM mod
2. Go into a map
3. Inject a human with the zombie syringe
4. See the results

I disabled every mod but the OCM mod and the issue persisted

 - **OS**: Windows 10  (10.0.19042) 64bit

 - **CPU**: Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz

 - **GPU**: Intel(R) HD Graphics 4600

 - **Memory**: 8 GB

Game Version: People Playground [v1.19.2] [64 bit]

**Comment by mestiez** [comment]
I cannot fix bugs this explicitly to do with mods.
