### ISSUE TITLE
objects won't collide with other objects if travelling and high speeds

### ISSUE THREAD

**Issue by 69Chosen69** [studio-minus/ppg-bug-reports#63]
**Describe the bug**
lets say you decided to hit someone with a bowling ball, you drag it at a high speed towards them but it phases through them

**Clearly describe how to reproduce the bug**
drag an object at high speeds towards another object

**Mod list**
no

**System info (please complete the following information)**
 - Operating system: x64
 - Game version:1.19.2
 - GPU:gtx 1060 ti
 - CPU:

**Additional notes**

**Comment by mestiez** [comment]
This is not a bug. You are in "discrete collision" mode. Switch to "continuous" in the settings.
