### ISSUE TITLE
resized wings accelerate infinitely

### ISSUE THREAD

**Issue by somepurplekale** [studio-minus/ppg-bug-reports#65]
**Describe the bug**
A wing that is resized to be very thin will generate force, doing loops that gradually increase in size and speed. 

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
spawn a wing
resize its y axis to be as small as possible

video
https://youtu.be/ij3QQswH-uA

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

active:
flipping heck
photo mode
halo weapons
controllable anti-air cannon
the steampunker
combat weapons pack v3.0

inactive:
depletable engines
doom weapons pack
lightsabers
the greenbrick mod

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.20 beta 1
 - GPU: Radeon RX 560X
 - CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx 2.10 GHz

**Additional notes**

**Comment by mestiez** [comment]
fixed 😎
