### ISSUE TITLE
resizing objects puts the center of mass in a visually incorrect place

### ISSUE THREAD

**Issue by somepurplekale** [studio-minus/ppg-bug-reports#66]
**Describe the bug**
Viewing a resized object with detail view shows the center of mass in an incorrect location. The actual center of mass seems to stay the same.

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
Some objects don't have this problem (ex: container wagon, wheel)
spawn an ak47
stretch the x axis
turn on detail view

turning on detail view while resizing the object lets you see the center of mass moving

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

active:
flipping heck
photo mode
halo weapons
controllable anti-air cannon
the steampunker
combat weapons pack v3.0

inactive:
depletable engines
doom weapons pack
lightsabers
the greenbrick mod

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.20 beta 1
 - GPU: RX 560X
 - CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx 2.10 GHz

**Additional notes**

**Comment by mestiez** [comment]
fixed :)
