### ISSUE TITLE
drawing bug

### ISSUE THREAD

**Issue by xXGhostBoyXx** [studio-minus/ppg-bug-reports#67]
**Describe the bug**
drawing bug
**Clearly describe how to reproduce the bug**
On Lava map, put a lot of atomic bombs on the bottom and detonate at the same time,
at the same time be at the maximum distance of vision
**Mod list**
No

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.20 preview
 - GPU: 
 - CPU: amd ryzen 3 2200g with radeon vega graphics(like so)

![image](https://user-images.githubusercontent.com/88079829/127285090-42232eed-e319-4a25-ba0e-f54d48d1f778.png)

**Comment by xXGhostBoyXx** [comment]
I just checked it, and saw that it is on every map, only it works on other maps, not always with an atomic bomb, sometimes with a fusion bomb

**Comment by mestiez** [comment]
fixed :)
