### ISSUE TITLE
Internal temp doesnt go up near lava

### ISSUE THREAD

**Issue by Stupter1** [studio-minus/ppg-bug-reports#68]
If ur near lava ur internal temp doesnt go up
beause normally u would sweat real hard if u were near lava that is really hot

I think you know what i mean it's just temp doesnt go up when near lava

**Mod list**
Everything deactivated
**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version:1.20.
 - GPU:GTX 1650 
 - CPU: Intel i5-10400-F

Thats all! thanks.

**Comment by mestiez** [comment]
this isnt really a bug. there is no heat radiation in the game. however, lava should emit ambient heat when ambient heat transfer is enabled.
