### ISSUE TITLE
Contraption loading for an unreasonably long (infinite) amount of time

### ISSUE THREAD

**Issue by WWWOWWWPL** [studio-minus/ppg-bug-reports#7]
**Describe the bug**
When loading the game on the 1.18 preview 1 version, a contraption (called MK-5 Samurai) seemed to be loading forever, effectively stopping the entire mod / contraption compiling. I looked up the contraption workshop page and it was gone, removed

**Clearly describe how to reproduce the bug**
Try to load in a mod that's been removed from the workshop? At least that's my guess

**Mod list**
I'd gladly post the entire list but as I said the game is stopping me from looking up my mods

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.18 preview 1
 - GPU: Nvidia GeForce 1050ti 4GB VRAM
 - CPU: Intel Core I5 7600k quad-core

**Additional notes**

**Comment by mestiez** [comment]
Fixed to an extent. There is now a timeout. For some reason I cannot check if something exists on the Workshop?? The documentation for this is a disaster.

Sidenote: 
> Mod list
I'd gladly post the entire list but as I said the game is stopping me from looking up my mods

There is a button in the "Information" section that will export all relevant debugging information.
