### ISSUE TITLE
Remove collision from items that can pierce.

### ISSUE THREAD

**Issue by Tye-Evans2** [studio-minus/ppg-bug-reports#70]
Found a way to remove collision from weapons that can pierce through the ground (by removing collision I mean from EVERYTHING even the ground)

Stab an item into the ground (spear works well) then freeze the item. Then pause the game and move it out of the ground. Then unpause the game and unfreeze item.

# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.19042) 64bit

 - **CPU**: Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz

 - **GPU**: NVIDIA GeForce GTX 1650

 - **Memory**: 7 GB

## All loaded mods

	Skullex(jamesH_2), Aspa102, Kassjak-Scream mod-2494555615 v1.0 for game v1.11
		Currently inactive

	Gun_O-Futuristic Weapons Mod +-2494447929 v0.3 for game v1.17
		Currently inactive

	Scringrandmaster347-Grasslands / Map-2489010038 v1.0 for game v1.17+
		Currently inactive

	Quickness-Iraq War mod-2467426507 v1.0 for game v1.16x
		Currently inactive

	Aspa102-Wheelchair-2455335631 v1.0 for game v1.16+
		Currently inactive

	Mini-Vamlejos (V1)-local v1.0 for game v1.14+
		Currently inactive

	Mini-Delta Aersea (V1)-local v1.0 for game v1.14+
		Currently inactive

	zooi-flipping heck-2448120172 v1.4 for game v1.16.2
		Currently ACTIVE
		Has been initialised

	Mini-Xioandia (V1)-local v1.0 for game v1.14+
		Currently inactive

	Mini-Whimule Planet (V1)-local v1.0 for game v1.14+
		Currently inactive

	Aspa102-Ocean-local v1.0 for game v1.14+
		Currently inactive

	kortl-COMBAT SPEC-OPS-local v1.0 for game v1.14
		Currently inactive

	Quickness-Lake Map-2434310949 v1.0 for game v1.14+
		Currently inactive

	Scriptmeat / Aspa102-TEST MAP 2-local v1.0 for game v1.14+
		Currently inactive

	ScriptMeat-TEST MAP-2403144679 v1.0 for game v1.14+
		Currently inactive

	ScriptMeat-Volcanic Map-2395054754 v1.1.2 for game v1.14+
		Currently inactive

	Avien Jones-Front Facing Human-local v1.0 for game v1.7
		Currently inactive

	ScriptMeat-Gravel, Sand and Water-2353091446 v1.0 for game v1.12+
		Currently inactive

	Skittles-Skittle's Syringe Mod-2268097682 v1.4 for game v1.19+
		Currently inactive

	Talonphobia-Syringes++-2146791852 v2.3 for game v1.12.2+
		Currently inactive

## Last log

```
312.8054s [LOG] Control scheme file not found.
312.8054s [EXCEPTION] FileNotFoundException: Could not find file "C:\Program Files (x86)\Steam\steamapps\common\People Playground\ControlScheme.json"
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean checkHost) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.StreamReader..ctor (System.String path) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
System.IO.File.ReadAllText (System.String path) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
InputSystem.Load () (at <2b83b641b72c48329c8bc2399bd00c95>:0)
UnityEngine.Debug:LogException(Exception)
InputSystem:Load()
ControlSchemeEditorBehaviour:LoadInputSystem()
ControlSchemeEditorBehaviour:Awake()
UnityEngine.GameObject:SetActive(Boolean)
MenuController:Awake()

312.8054s [LOG] {
  "DropOnDeath": true,
  "LimbCrushing": true,
  "LimbOverflowExplosion": true,
  "TracerBullets": true,
  "FancyEffects": true,
  "ExpandedGore": false,
  "Decals": true,
  "ClampVolume": true,
  "ShowOutlines": true,
  "LogDebugMessages": false,
  "ShowFramerate": true,
  "Lighting": true,
  "VSync": false,
  "SMAA": false,
  "ZoomSensitivity": 1.0,
  "MasterVolume": 1.0,
  "SfxVolume": 1.0,
  "UserInterfaceVolume": 1.0,
  "AmbienceVolume": 1.0,
  "ShakeIntensity": 1.0,
  "SlowMotionSpeed": 20.0,
  "CrushForceMultiplier": 1.0,
  "DeleteWireByContextMenu": true,
  "SimplifiedBackground": false,
  "AmbientTemperatureTransfer": true,
  "TemperatureUnit": 0,
  "WindowMode": 1,
  "CollisionQuality": 1,
  "TonemappingMode": 0,
  "BloomMode": 2,
  "Brightness": 100.0,
  "PhysicsIterations": 16,
  "RenderScale": 1.0,
  "FramerateLimit": 144,
  "Resolution": null,
  "ShowTutorial": false,
  "ShowModLoadingFreeze": true,
  "RejectShadyCode": true
}
```

**Comment by mestiez** [comment]
fixed :D
