### ISSUE TITLE
Ion Thrusters Glitch out Under Lava

### ISSUE THREAD

**Issue by UnHoly-Water** [studio-minus/ppg-bug-reports#72]
**Describe the bug**
When Ion Thrusters are submerged under lava they freak out and launch themselves in a random direction at high velocities

**Clearly describe how to reproduce the bug**
Enter the Lava Map
Spawn in an ion thruster under lava
Observe the chaos

**Mod list**
All mods in my list are deactivated
Liquid-related Machinery by Jimmyl
FleasyWeapons - Small Guns by Fleasy
Raw Pink Liquids by davidco7777
Pickle Human by zack1010101
throwing knife by krzem
small acid swamps by ahlad
More Daggers by Burgerek_P1
Injectable Flasks Mod by PersonMan85
TABS Mod by IaMFreezz
Simple Syringes Mod by Pumpkin
Liquidentifier Reskin by sneby
Literally a Pickle by jimzzyy
Emergency Siren by MR.REX
H.U.M.A.N Tech Mod by Human Tech Industries for Anything think lol
Signals and Logic Gates by zooi
The Musket Mod by Mr_kWKD
Decomposition by The Ninja Scout
Scream Mod by Skullex(jamesH_2)
Women Mod by Holy_Water
Generators+ by yefeyke
Nuclear PLayground by Kubulll
1000 Degree Knife by Skittles
Greenbrick Industries by Talonphobia
Woman mod by FredMichealBear
More Explosives by Crafter_215
CRT Televisions! by Soiled Panties
Taser by Morzzie
ExplosiveMod by Jimmyl
Among Us Mod by Golden, Talon Zane
Hazmat Mod Remasterd by Golden
Duel Lightsabers 2.5 by Kyrelink and Sorofotune
Functioning Armor by weirdo
Purple mod 2 by DRAGOLITE
The Tungsten Mod by Kelly The Dragon
BloodEye3 by Woowz11
Active Humans by quaq
Syringes++ by Talonphobia
Katana Mod by Portal Turret1010

That took awhile to type

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.20 + Open Beta
 - GPU: Nvidia RTX 2070 Super
 - CPU: Intel I7-10700

**Additional notes**
Bring back the discord server please

**Comment by UnHoly-Water** [comment]
After throwing every item in the game into lava this seams to only be an issue with the table, stormbann, and ion thruster

**Comment by UnHoly-Water** [comment]
This also happens when Ion Thrusters are on top of sliders and moving quickly

**Comment by mestiez** [comment]
good report. it has been fixed
