### ISSUE TITLE
Filled empty syringe (not empty anymore) still has no effects

### ISSUE THREAD

**Issue by SoySmash** [studio-minus/ppg-bug-reports#76]
**Describe the bug**
Adding liquid to a empty syringe can have no effect

**how to reproduce the bug**
Place for example, a Death syringe and a bone breaking syringe (any syringe works) and set a blood tank to pull, hook them up to the blood tank. and then hook it up to a empty syringe, once the syringe is filled up unhook it and stab someone with it, nothing happens. (the syringe has absolutely no effect) the flasks do work tho.

**Mod list**
Currently no mods installed

**System info**
 - Operating system: Windows 10
 - Game version: 1.20
 - GPU: I don't know
 - CPU: I don't know

**Comment by mestiez** [comment]
The empty syringe is set to "pull mode" when spawned. You can tell by seeing which way the line on the syringe moves. If it moves towards the tip, it's set to push mode. Activating a syringe toggles between push & pull mode.

**Comment by SoySmash** [comment]
> The empty syringe is set to "pull mode" when spawned. You can tell by seeing which way the line on the syringe moves. If it moves towards the tip, it's set to push mode. Activating a syringe toggles between push & pull mode.

thanks, i did not know that
