### ISSUE TITLE
bug with hurt

### ISSUE THREAD

**Issue by YOPLAY13** [studio-minus/ppg-bug-reports#78]
**Describe the bug**
it's a part of "bug with limbs"

**Clearly describe how to reproduce the bug**
when I take a limb and poke it with a knife, for some reason it hurts a person, although it is no longer a part of his body
**Mod list**
(syringes++)  not active

**System info (please complete the following information)**
 - Operating system: win 10 pro
 - Game version: 1.20
 - GPU: RX 570 4gb
 - CPU: Ryzen 5 1400

**Additional notes**
i already write issue, but with heating element

**Comment by mestiez** [comment]
fixed :}
