### ISSUE TITLE
zombie syringe bug

### ISSUE THREAD

**Issue by LijmPistool** [studio-minus/ppg-bug-reports#8]
**Describe the bug**
the frozen blue effect goes away when using the zombie syringe in temps from 0 or higher

**Clearly describe how to reproduce the bug**
change the ambient temp to below zero, spawn human and make sure he is blue (frozen) change temp to 0 or higher and use the zombie syringe on him.. you see that he instantly unfreezes and becomes a zombie

**Mod list**
I deactivated all the mods to test this

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.18 preview 1
 - GPU: NVIDIA GeForce GTX 1050
 - CPU: AMD Ryzen 5 2600 Six-Core Processor

**Additional notes**
sorry voor mijn slechte Engels, ik heb mijn best gedaan

**Comment by mestiez** [comment]
is helemaal ok vriend

**Comment by mestiez** [comment]
I think he might be unfreezing because he is revived and his body regains body temperature? It's hard to tell. 
> But you wrote this whole system, how can you be confused about how it works????
I have brain damage.
