### ISSUE TITLE
[Small Bug]Tempered Glass

### ISSUE THREAD

**Issue by AlviMC** [studio-minus/ppg-bug-reports#81]
**Describe the bug**
Tempered glass comes back to the default size when in damaged state rather than staying on modified size.

**Clearly describe how to reproduce the bug**
This bug can be achieved whenever you resize an tempered glass and damage it until it comes to the broken status.

**Mod list**
Tested without mods

**System info (please complete the following information)**
This should not matter but here we go...:P
 - Operating system: Windows 10 Home x64
 - Game version: 1.20
 - GPU: 1050 (2GB)
 - CPU: i5-7300HQ

**Additional notes**

**Comment by trollAgeS** [comment]
This happens to anything thats breakable being resized like pumpkins, brick walls, crates, etc.

**Comment by mestiez** [comment]
fixed :)
