### ISSUE TITLE
Fusion Bomb Hybrid Map Dissapearence

### ISSUE THREAD

**Issue by teaposed** [studio-minus/ppg-bug-reports#82]
**Describe the bug**
As the name says, there is a problem where the Fusion Bomb and Lava make the Hybrid map dissapear.

**how to reproduce the bug**
To reproduce this bug you have to let the Fusion Bomb fall into the Lava and then activate it like a second later after it hits the lava.

**Mod list**
         

	Aspa102-OCM-2508897711 v2.0 for game v1.19
		Currently ACTIVE
		Has been initialised

	Blocksify & Frevv-Blocksify's Crazy Syringes Mod-2498890172 v1,000,000 for game v1.18
		Currently inactive

	zooi-flipping heck-2448120172 v1.4 for game v1.16.2
		Currently ACTIVE
		Has been initialised

	Morzzic-Aimbot Gun-local v1.0 for game v1.8.1
		Currently ACTIVE

	Adskiy Drochila & Woowz11-Madness PACK-2299286896 v1.6.0 for game v1.12.2
		Currently ACTIVE

	enigmaburrito21-Hitman Mod-2279170186 v1.5 for game v1.10+
		Currently inactive

	weirdo-Advanced Damage-2212880187 v2.0 for game v1.17
		Currently ACTIVE

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently inactive

	Kyrelink-Minecraft Blocks mod-local v1.0 for game v1.7
		Currently inactive

	G-TRiXER and Farsh-The Infinity Weapons Pack-2140597243 v1.1 for game v1.8+
		Currently inactive

	Kyrelink-Half Life 2 weapons-2140530282 v1.6 for game v1.7
		Currently inactive

	Ladno.-StalkerWeaponsMod-2140155327 v2.0 for game v1.9+
		Currently inactive

	Farsh-The Banalnoe TV Medal-local v1.0 for game v1.8
		Currently inactive

	(RU)Enot builder-Weapon Mod-2137486750 v0.8 for game v1.7x
		Currently inactive

	DANBALL-JMod-2130445408 v2.2 for game v1.8
		Currently inactive

**System info (please complete the following information)**
-OS: Windows 10  (10.0.19043) 64bit

-Game Version: 1.20

-CPU: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

- GPU: NVIDIA GeForce GTX 1650

**Comment by mestiez** [comment]
Fixed
