### ISSUE TITLE
All the wires of contraptions/copies have been removed

### ISSUE THREAD

**Issue by DindinYT37** [studio-minus/ppg-bug-reports#83]
**Describe the bug**
(Own contraptions) All the wires of contraptions made before 1.19 have been removed.
(Workshop contraptions) All the wires have been removed regardless of the version.

If I spawn a contraption or paste something I copied "deserialization error" is what meets me in the logs, all the wires are removed and anything a human wielded is dropped as well.

**Clearly describe how to reproduce the bug**
~~I don't have clear steps to reproduce this, it just happened without any obvious reason.~~
For Contraptions: None.
Copies: I just copy something with wires and when I paste it that happens.

**Mod list**
No updates happened and it wasn't because of any mod since I didn't add one recently.
_[exported game debug info.md](https://github.com/studio-minus/ppg-bug-reports/files/6949573/exported.game.debug.info.md)_

**System info (please complete the following information)**
 - Operating system: Windows 10 (64x)
 - Game version: 1.20
 - GPU: NVIDIA GeForce GTX 1070
 - CPU: AMD Ryzen 7 2700X

**Comment by mestiez** [comment]
Can you send me the contraption files?

**Comment by DindinYT37** [comment]
Here is a contraption that isn't working for me
[Toilet.zip](https://github.com/studio-minus/ppg-bug-reports/files/6950535/Toilet.zip)

**Comment by mestiez** [comment]
Can't reproduce this. Must be caused by a mod. Try disabling all mods one by one to see which one is causing the issue.
