### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by KomodoBro** [studio-minus/ppg-bug-reports#84]
Whenever I try to save a contraption, it sometimes will save or will not save, I usually spend 1 hour creating a map for myself to start like a war on, I spent like 1 hour working on a map it looked pretty good, I saved it and I closed PPG, when I went on 2 hours later the map didn't save, recently I was working on a different map I was saving the shell of it and it won't save I tried to save again and PPG crashed, I went back on and it didn't save

You really don't need to do anything you just need to save.

Mod list

Hold K to make wires invisible :On
Active Humans Mod :Off
Humans+ :Off
The Tungsten Mod :Off
Stay Wars Infantry mod 1.4 :Off
Functioning Armor :Off
Smart Spawner :Off          
Advanced Damage :Off 
Hazmat Mod Remastered :Off 
Chemical Warfare :Off 
Star Wars side characters :on 
Powers Mod: Off
Human Tiers :Off 
S.C.P.F Mod :On 
Star Wars Darksaber :Off 
Mulligan :Off 
Marvel Power Pack :On 
City People :Off 
Alien VS Predator Mod :Off 
Android Injectors :Error 
SCP Foundation Expanded :Off 
Vanilla Weapons Plus 2 :Off 
Police + :Off 
Baton Empire Stuff :On 
Map Blocks :On 
Imperial Weapons :On 
More Weapons Mod :Off 
Doom 3 Mod :Off 
LEGION :On 
Imperial NPC Pack 0.4 :Off 
Greenbrick Industries :ERROR
Veliceraptor Mod :Off 
Nuclear Playground :Off 
More Android  :On 
Auto-9 :On 
SUPER DROIDS MOD :Off 
Test Subjects+ :Off 
Dead No Collide :Off 
Metal Humans :Off 
Zenit Project Minus :On 
HI-TECH SOLDIERS AND WEAPONS MOD :Off 
Apex Legends Stuff :On 
Liquid Related Machinery :On 
Adeptus Mechanicus :Off 
Space Mod :On 
Mini's Arsenal :Off 
Raw Pink Liquids :On 
DuraHuman :Off 
Massa Cooperation Items :On 
Slow Acting Regen Syringe :Off 
Hau'Tne Empire :On 
More Chainsaws :Off 
Guns,guns,guns! :Off 
Thermal Devices :Off 
The Ultimate Human Mod :On 
Emergency Siren :Off 
OCM :On 
Abomination :Off 
Quality Of Life Items :On 
Roblox Isle :Off 
Isle Mod :Off 
Futuristic Weapons Mod+ :Off 
Colored I-Beams Mod :Off 

System info (please complete the following information)
 - Operating system:  Dell Latitude 
 - Game version: 1.20 - Not Beta
 - GPU: NVIDIA GeForce GT 720M 2GB Graphics Card
 - CPU: Intel Atom
Yeah my PC is trash.

Additional notes

I am screaming and I want to throw my pc out my window, and my hands hurt from typing all of my mods out.

**Comment by mestiez** [comment]
> I am screaming and I want to throw my pc out my window, and my hands hurt from typing all of my mods out.

Use "Export game debug info" next time lol

**Comment by mestiez** [comment]
This is caused by a mod you have installed. Try disabling OCM first (because it's the most complicated) and then every other mod one-by-one, trying to reproduce the bug in between. This will tell you what mod is causing the issue.

**Comment by KomodoBro** [comment]
Okay, another issue has happened, every time I load a build the wires aren't there and it falls apart.

**Comment by KomodoBro** [comment]
And whenever I use Z on any loaded contraption it is still there

**Comment by KomodoBro** [comment]
I hope I fixed it.

**Comment by KomodoBro** [comment]
![image](https://user-images.githubusercontent.com/88641283/128784571-453da833-a549-425b-88b1-c048bb1da2f9.png)
I uninstalled OCM

**Comment by KomodoBro** [comment]
Its still doing it,

**Comment by KomodoBro** [comment]
I disabled every mod.

**Comment by KomodoBro** [comment]
I fixed it.

**Comment by mestiez** [comment]
How?

**Comment by KomodoBro** [comment]
It was OCM
