### ISSUE TITLE
stdErrOut error: in mods

### ISSUE THREAD

**Issue by dzinsak** [studio-minus/ppg-bug-reports#85]
**Describe the bug**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Mod list**
metal people error

**System info (please complete the following information)**
 - Operating system: windows
 - Game version: 1.20
 - GPU:
 - CPU: AMD Athlon(tm) II X2 250

**Additional notes**

**Comment by mestiez** [comment]
This is a worthless bug report. Please fill out the requrest information next time.
