### ISSUE TITLE
Jelly Bean People

### ISSUE THREAD

**Issue by Zer1op** [studio-minus/ppg-bug-reports#88]
**Describe the bug**
Humans and robots can't normally stop. Their joints are jumping like jelly.

**Clearly describe how to reproduce the bug**
You just need to spawn Human or Robot to reproduce it

**Mod list**
All the mods are deactivated

**System info (please complete the following information)**
 - Operating system: Windows 10 Home (x64)
 - Game version: 1.20
 - GPU: MSI GeForce GTX 1650
 - CPU: Intel Core i5 9400F

 [exported game debug info.md](https://github.com/studio-minus/ppg-bug-reports/files/6961134/exported.game.debug.info.md)

**Additional notes**
It's impossible to play with this bug, fix it, please 8)

**Comment by mestiez** [comment]
It is not a bug. You have set your Physics Iteration settings to 1 iteration. The default value is 16.
