### ISSUE TITLE
Keyboard doesn't work

### ISSUE THREAD

**Issue by FreewayCola** [studio-minus/ppg-bug-reports#94]
**Describe the bug**
Keyboard doesn't work, all keybind are set but game seems just don't read them. Only working thing is mouse but only with side panels. It only happening after loading map, keyboard in main menu is perfectly fine (I was able to change keybind in options)

**Clearly describe how to reproduce the bug**

1. Open Game
2. Load map 

**Mod list**
I removed all my mods from my workshop and issue still occurs

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.21 beta 1
 - GPU: GTX 1050ti
 - CPU: Intel core i5-8400 cpu 2.80ghz

**Comment by 1xev3** [comment]
Same

**Comment by mestiez** [comment]
Fixed
