### ISSUE TITLE
Bone eating syringe/flesh eating syringe bug

### ISSUE THREAD

**Issue by Firehawk596** [studio-minus/ppg-bug-reports#96]
**Describe the bug**
If you inject a human with a bone-eating syringe and then a flesh-eating syringe, the human still has bones.

**Clearly describe how to reproduce the bug**
you need to inject the human with a bone-eating syringe and then a flesh eating syringe.
**Mod list**
I have these mods in use but none are activated
https://steamcommunity.com/sharedfiles/filedetails/?id=2163278857
https://steamcommunity.com/sharedfiles/filedetails/?id=2389733225
https://steamcommunity.com/sharedfiles/filedetails/?id=2389733225
https://steamcommunity.com/sharedfiles/filedetails/?id=2235585600
https://steamcommunity.com/sharedfiles/filedetails/?id=2308911224
https://steamcommunity.com/sharedfiles/filedetails/?id=2226697361
https://steamcommunity.com/sharedfiles/filedetails/?id=2226697361
**System info (please complete the following information)**
 - Operating system:  windows
 - Game version: open beta
 - GPU: AMD Ryzen 5 5500U
 - CPU: Radeon Graphics 2.10 GHz

**Comment by mestiez** [comment]
Not a bug, simply misnamed
