### ISSUE TITLE
Weapons visual bug.

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bug-reports#97]
**Describe the bug**
Moving weapon parts have layer is onfront of human when main gun is not.

**Clearly describe how to reproduce the bug**
https://www.youtube.com/watch?v=enu63O-b7FM

**Mod list**
   No mods.

**System info (please complete the following information)**
 - Operating system: win 10
 - Game version: 1.21 beta
 - GPU: Nvidia geforce 750 TI
 - CPU: Intel Core I3-3240 3.40 GHz

**Comment by mestiez** [comment]
Fixed
