### ISSUE TITLE
Missile launcher laser bug.

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bug-reports#98]
When missile launcher spawned by Q its laser is broken.

https://youtu.be/ErQJXE1-5mc

No mods enabled.

 - Operating system: win 10
 - Game version: 1.21 beta
 - GPU: Nvidia geforce 750 TI
 - CPU: Intel Core I3-3240 3.40 GHz

**Comment by mestiez** [comment]
Fixed :)
