### ISSUE TITLE
Debris deletion bug.

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bug-reports#99]
Debris cannot be deleted by Z.

Spawn brick wall or other destructible item, break it and try to delete with Z.

No mods enabled

 - Operating system: win 10
 - Game version: 1.21 beta
 - GPU: Nvidia geforce 750 TI
 - CPU: Intel Core I3-3240 3.40 GHz

**Comment by mestiez** [comment]
Fixed :)
